// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvJl3GaowKEAhj3Bnl13Zt3N_5vJTke44',
    appId: '1:1099137452041:web:96f0296a837e410af190d8',
    messagingSenderId: '1099137452041',
    projectId: 'mini-ecommerce-app-17e86',
    authDomain: 'mini-ecommerce-app-17e86.firebaseapp.com',
    storageBucket: 'mini-ecommerce-app-17e86.appspot.com',
    measurementId: 'G-7XY1P1KS1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC62yZWc8g5wGZ17o9EQ-luIIUJeQR7IIU',
    appId: '1:1099137452041:android:a82310231dcad9a9f190d8',
    messagingSenderId: '1099137452041',
    projectId: 'mini-ecommerce-app-17e86',
    storageBucket: 'mini-ecommerce-app-17e86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGVakPPN4-gdfyOG_BeHoIoY2mz25POcg',
    appId: '1:1099137452041:ios:a5f3f1fe4480b0f0f190d8',
    messagingSenderId: '1099137452041',
    projectId: 'mini-ecommerce-app-17e86',
    storageBucket: 'mini-ecommerce-app-17e86.appspot.com',
    iosBundleId: 'com.example.miniEcommerceAppAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGVakPPN4-gdfyOG_BeHoIoY2mz25POcg',
    appId: '1:1099137452041:ios:e71ee5c5fe965672f190d8',
    messagingSenderId: '1099137452041',
    projectId: 'mini-ecommerce-app-17e86',
    storageBucket: 'mini-ecommerce-app-17e86.appspot.com',
    iosBundleId: 'com.example.miniEcommerceAppAssignment.RunnerTests',
  );
}
